export const TRAILING_ENTRY_TYPE = {
    SHORT_CASE_1_2_3: 'SHORT_CASE_1_2_3',
    SHORT_CASE_1: 'SHORT_CASE_1',
    SHORT_CASE_2: 'SHORT_CASE_2',
    SHORT_CASE_3: 'SHORT_CASE_3',
    SHORT_CASE_4: 'SHORT_CASE_4',
    SHORT_CASE_5: 'SHORT_CASE_5',

    LONG_CASE_1: 'LONG_CASE_1',
    LONG_CASE_2: 'LONG_CASE_2',
    LONG_CASE_3: 'LONG_CASE_3',
    LONG_CASE_4: 'LONG_CASE_4',
    LONG_CASE_5: 'LONG_CASE_5',
};

export const TRAILING_CLOSING_TYPE = {
    CLOSE_LONG_CASE_1: 'CLOSE_LONG_CASE_1',
    CLOSE_LONG_CASE_2: 'CLOSE_LONG_CASE_2',
    CLOSE_LONG_CASE_3: 'CLOSE_LONG_CASE_3',

    CLOSE_SHORT_CASE_1: 'CLOSE_SHORT_CASE_1',
    CLOSE_SHORT_CASE_2: 'CLOSE_SHORT_CASE_2',
    CLOSE_SHORT_CASE_3: 'CLOSE_SHORT_CASE_3',
};

export const INDICATOR_SOURCE_OPEN = 'open';
export const CLOSE_BY_RATE_REASON = 'CLOSE_BY_RATE';
export const CLOSE_BY_SIGNAL = 'NORMAL';
export const CLOSING_SCALE_ALL = 'all';
